//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos.Conexiones.Planillas_SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aguinaldo
    {
        public int ID_Aguinaldo { get; set; }
        public int ID_Empleado { get; set; }
        public Nullable<int> MesesAplicados { get; set; }
        public Nullable<decimal> Monto_Total { get; set; }
        public Nullable<int> Anio { get; set; }
        public System.DateTime Fecha_Generacion { get; set; }
        public int UsuarioCreador { get; set; }
        public int UltimoUsuarioActualizador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltActualizacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual TLUsuario TLUsuario { get; set; }
        public virtual TLUsuario TLUsuario1 { get; set; }
    }
}
