//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos.Conexiones.Planillas_SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDeduccione
    {
        public int ID_DetalleDeducciones { get; set; }
        public int ID_Deducciones { get; set; }
        public int ID_PeriodoDePLanilla { get; set; }
        public Nullable<decimal> Cuota { get; set; }
        public Nullable<int> Cuota_Actual { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public int UsuarioCreador { get; set; }
        public int UltimoUsuarioActualizador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltActualizacion { get; set; }
    
        public virtual Deduccione Deduccione { get; set; }
        public virtual PeriodoDePLanilla PeriodoDePLanilla { get; set; }
        public virtual TLUsuario TLUsuario { get; set; }
        public virtual TLUsuario TLUsuario1 { get; set; }
    }
}
