//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos.Conexiones.Planillas_SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Aguinaldoes = new HashSet<Aguinaldo>();
            this.ControlVacaciones = new HashSet<ControlVacacione>();
            this.Deducciones = new HashSet<Deduccione>();
            this.HorasLaboradas = new HashSet<HorasLaborada>();
            this.Incapacidades = new HashSet<Incapacidade>();
            this.Liquidaciones = new HashSet<Liquidacione>();
            this.PlanillaDetalles = new HashSet<PlanillaDetalle>();
        }
    
        public int ID_Empleado { get; set; }
        public int ID_Persona { get; set; }
        public int ID_Puesto { get; set; }
        public int ID_Departamento { get; set; }
        public int ID_Activo { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public int Total_Vacaciones { get; set; }
        public System.DateTime Fecha_de_ingreso { get; set; }
        public decimal Salario { get; set; }
        public int UsuarioCreador { get; set; }
        public int UltimoUsuarioActualizador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltActualizacion { get; set; }
    
        public virtual Activo Activo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aguinaldo> Aguinaldoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlVacacione> ControlVacaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deduccione> Deducciones { get; set; }
        public virtual TLDepartamento TLDepartamento { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Puesto Puesto { get; set; }
        public virtual TLUsuario TLUsuario { get; set; }
        public virtual TLUsuario TLUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorasLaborada> HorasLaboradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incapacidade> Incapacidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liquidacione> Liquidaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaDetalle> PlanillaDetalles { get; set; }
    }
}
