//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos.Conexiones.Planillas_SQLServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaControlPlanillaEntities : DbContext
    {
        public SistemaControlPlanillaEntities()
            : base("name=SistemaControlPlanillaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activo> Activoes { get; set; }
        public virtual DbSet<Aguinaldo> Aguinaldoes { get; set; }
        public virtual DbSet<ControlVacacione> ControlVacaciones { get; set; }
        public virtual DbSet<Deduccione> Deducciones { get; set; }
        public virtual DbSet<DetalleDeduccione> DetalleDeducciones { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<EstadoVacacione> EstadoVacaciones { get; set; }
        public virtual DbSet<HorasLaborada> HorasLaboradas { get; set; }
        public virtual DbSet<Incapacidade> Incapacidades { get; set; }
        public virtual DbSet<Liquidacione> Liquidaciones { get; set; }
        public virtual DbSet<PeriodoDePLanilla> PeriodoDePLanillas { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Planilla> Planillas { get; set; }
        public virtual DbSet<PlanillaDetalle> PlanillaDetalles { get; set; }
        public virtual DbSet<Puesto> Puestoes { get; set; }
        public virtual DbSet<Tipo_Multiplicador> Tipo_Multiplicador { get; set; }
        public virtual DbSet<Tipo_Remuneracion> Tipo_Remuneracion { get; set; }
        public virtual DbSet<TIpoDeduccione> TIpoDeducciones { get; set; }
        public virtual DbSet<TipoDeResponsabilidad> TipoDeResponsabilidads { get; set; }
        public virtual DbSet<TIpoDeSalida> TIpoDeSalidas { get; set; }
        public virtual DbSet<TLDepartamento> TLDepartamentoes { get; set; }
        public virtual DbSet<TLUsuario> TLUsuarios { get; set; }
    }
}
