//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos.Conexiones.Planillas_SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorasLaborada
    {
        public int ID_HorasLaboradas { get; set; }
        public int ID_Empleado { get; set; }
        public int ID_Tipo_Remuneracion { get; set; }
        public int ID_PeriodoDePLanilla { get; set; }
        public System.DateTime Fecha_Ejecucion { get; set; }
        public int CantidadDeHOras { get; set; }
        public decimal Salario_Referencia { get; set; }
        public string Motivo { get; set; }
        public int UsuarioCreador { get; set; }
        public int UltimoUsuarioActualizador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltActualizacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual PeriodoDePLanilla PeriodoDePLanilla { get; set; }
        public virtual Tipo_Remuneracion Tipo_Remuneracion { get; set; }
        public virtual TLUsuario TLUsuario { get; set; }
        public virtual TLUsuario TLUsuario1 { get; set; }
    }
}
