//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos.Conexiones.Planillas_SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Empleadoes = new HashSet<Empleado>();
            this.TLUsuarios = new HashSet<TLUsuario>();
        }
    
        public int ID_Persona { get; set; }
        public string Nombre { get; set; }
        public string Apelllido1 { get; set; }
        public string Apellido2 { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TLUsuario> TLUsuarios { get; set; }
    }
}
