//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos.Conexiones.Planillas_SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillaDetalle
    {
        public int ID_PlanillaDetalle { get; set; }
        public int ID_Empleado { get; set; }
        public int ID_Planilla { get; set; }
        public System.DateTime Fecha_Generacion { get; set; }
        public Nullable<decimal> Salario_Bruto { get; set; }
        public Nullable<decimal> Salario_Neto { get; set; }
        public Nullable<decimal> CCSS_Impuesto { get; set; }
        public Nullable<decimal> Deducciones { get; set; }
        public int UsuarioCreador { get; set; }
        public int UltimoUsuarioActualizador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltActualizacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Planilla Planilla { get; set; }
        public virtual TLUsuario TLUsuario { get; set; }
        public virtual TLUsuario TLUsuario1 { get; set; }
    }
}
