//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos.Conexiones.Planillas_SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planilla()
        {
            this.PlanillaDetalles = new HashSet<PlanillaDetalle>();
        }
    
        public int ID_Planilla { get; set; }
        public int ID_PeriodoDEPLanilla { get; set; }
        public string Descripcion { get; set; }
        public int UsuarioCreador { get; set; }
        public int UltimoUsuarioActualizador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltActualizacion { get; set; }
    
        public virtual PeriodoDePLanilla PeriodoDePLanilla { get; set; }
        public virtual TLUsuario TLUsuario { get; set; }
        public virtual TLUsuario TLUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaDetalle> PlanillaDetalles { get; set; }
    }
}
