//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos.Conexiones.Planillas_SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeResponsabilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoDeResponsabilidad()
        {
            this.TIpoDeSalidas = new HashSet<TIpoDeSalida>();
        }
    
        public int ID_TipoDeResponsabilidad { get; set; }
        public string Nombre { get; set; }
        public int UsuarioCreador { get; set; }
        public int UltimoUsuarioActualizador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltActualizacion { get; set; }
    
        public virtual TLUsuario TLUsuario { get; set; }
        public virtual TLUsuario TLUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIpoDeSalida> TIpoDeSalidas { get; set; }
    }
}
